version: '3'
services:

  app:
    build: .
    command: sh -c "./run-test.sh"
    environment:
      PGUSER: andre_paes
      PGPASSWORD: postgres
      PGDATABASE: api_banking_test
      PGPORT: 5432
      PGHOST: db_test
      TEST_DB: db_test
    ports:
      - "4000:4000"
    working_dir: /app
    depends_on:
      - db_test
    networks:
      - backend
    volumes:
      - ./:/app

  db_test:
    image: postgres:latest
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: andre_paes
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_banking_test
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    networks:
      - backend
volumes:
  pgdata_test:

networks:
  backend:
    driver: bridge