version: '3'
services:

  app:
    build:
      context: .
    environment: 
      PGUSER: andre_paes
      PGPASSWORD: postgres
      PGDATABASE: api_banking_dev
      PGPORT: 5432
      PGHOST: db
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment: 
      POSTGRES_USER: andre_paes
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_banking_dev
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes: 
  pgdata: