version: '3'
services:

  app:
    build:
      context: .
    environment: 
      PGUSER: andre_paes
      PGPASSWORD: postgres
      PGDATABASE: api_banking_dev
      PGHOST: db
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: andre_paes
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_banking_dev
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - /.:/app
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - backend

  db1:
    image: postgres:latest
    environment:
      POSTGRES_USER: andre_paes
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_banking_test
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - ./pgdata_test:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge