version: '3'
services:

  app:
    build: .
    command: sh -c "./run.sh"
    environment: 
      PGUSER: andre_paes
      PGPASSWORD: postgres
      PGDATABASE: api_banking_dev
      PGPORT: 5432
      PGHOST: db
      DB_LOCATION: db_test
    ports:
      - "4000:4000"
    working_dir: /app
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - ./:/app

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: andre_paes
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_banking_dev
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - /.:/app
      - pgdata_dev:/var/lib/postgresql/data
    networks:
      - backend

  db_test:
    image: postgres:latest
    environment:
      POSTGRES_USER: andre_paes
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_banking_test
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata_test:/var/lib/postgresql/data

volumes:
  pgdata_test:
  pgdata_dev:

networks:
  backend:
    driver: bridge